Repository ba-latex/Vorlage-Latex, pull requests merged in 2021-08, with the labels that each got.

#78 bump buildcontainer -> v1.5.0 und diff-pdf
  .github/workflows/document-build.yml
  .gitignore
  .vscode/settings.json
  .vscode/tasks.json
Labels: enhancement, workflow/tools, build: container

#81 mini-fix weil colin doof ist
  .vscode/tasks.json
Labels: bug

#83 fix für kaputte diff-action auf neuem branch
  .github/workflows/document-build.yml
Labels: bug, workflow/tools

#85 Pakete hinzugefügt
  Latex/vorlage.tex
Labels: enhancement

#87 bump buildcontainer -> v1.5.1
  .vscode/settings.json
Labels: enhancement, build: container

#84 🤯 release v2
  .github/workflows/document-build.yml
  .gitignore
  .gitpod.yml
  .vscode/keybindings.json
  .vscode/settings.json
  .vscode/tasks.json
  HINWEISE.md
  Latex/inhalt/Anhang.tex
  Latex/metadaten.sty
  Latex/vorlage.tex
Labels: release

#90 README.md angepasst
  README.md
Labels: documentation, enhancement

#89 readme-updates und keybindings-fix (soll noch in v2)
  .vscode/keybindings.json
  HINWEISE.md
  README.md
Labels: bug, documentation, release, tools: vscode

#92 Dev hotfix des hotfix weil @DSczyrba ungeduldig ist
  Latex/inhalt/Abkürzungen.tex
  Latex/inhalt/Anhang.tex
  Latex/inhalt/Kapitel1.tex
Labels: enhancement

#106 Abstract und Freigabeerklärung
  Latex/inhalt/Abstract_Freigabeerklärung_Bachelorthesis.tex
  Latex/inhalt/Anhang.tex
  Latex/inhalt/Erklärung_3Autoren.tex
  Latex/inhalt/Erklärung_Praxisbeleg.tex
  Latex/metadaten.sty
Labels: enhancement

#109 Gesammelte Änderungen und Fixes
  .github/workflows/document-build.yml
  .gitpod.yml
  HINWEISE.md
  Latex/bilder/ba_glauchau_logo.svg
  Latex/bilder/logo.png
  Latex/bilder/schaltung1.png
  Latex/inhalt/Abkürzungen.tex
  Latex/inhalt/Abstract_Freigabeerklärung_Bachelorthesis.tex
  Latex/inhalt/Anhang.tex
  Latex/inhalt/Einleitung.tex
  Latex/inhalt/Erklärung_3Autoren.tex
  Latex/inhalt/Erklärung_Praxisbeleg.tex
  Latex/inhalt/Fazit.tex
  Latex/inhalt/Kapitel.tex
  Latex/inhalt/Kapitel1.tex
  Latex/inhalt/Kapitel2.tex
  Latex/inhalt/Kapitel3.tex
  Latex/inhalt/Kapitel4.tex
  Latex/inhalt/LIES MICH.txt
  Latex/inhalt/Titelseite_3Autoren.tex
  Latex/light/vorlage_light.tex
  Latex/literatur.bib
  Latex/main.tex
  Latex/metadaten.sty
  Latex/vorlage.tex
  sortieren.py
Labels: documentation, enhancement, release
