Repository ba-latex/Vorlage-Latex, pull requests merged in 2021-09, with the labels that each got.

#116 Veraltete Extension durch VS Code natives Setting ersetzt
  .vscode/extensions.json
  .vscode/settings.json
Labels: bug, enhancement

#117 Neuere Statusbar Commands Versionen freigeben
  .gitpod.yml
Labels: enhancement

#119 Gitpod: bump latex workshop
  .gitpod.yml
Labels: bug, enhancement, tools: gitpod

#121 Minted Style verbessert / Container Version Bump / Dateiendungen entfernt
  .vscode/settings.json
  Latex/inhalt/Abstract_Freigabeerklärung_Bachelorthesis.tex
  Latex/inhalt/Anhang.tex
  Latex/inhalt/Erklärung_3Autoren.tex
  Latex/inhalt/Erklärung_Praxisbeleg.tex
  Latex/inhalt/Kapitel1.tex
  Latex/light/vorlage_light.tex
  Latex/main.tex
  Latex/vorlage.tex
Labels: bug, enhancement

#120 bracket pair colorizer aus gitpod entfernen
  .gitpod.yml
Labels: enhancement, tools: gitpod

#123 Nachnamen automatisch in CAPS, maximal 3
  Latex/literatur.bib
  Latex/vorlage.tex
Labels: enhancement

#125 Mehrere Autoren
  Latex/literatur.bib
  Latex/vorlage.tex
Labels: bug

#127 Struktur angepasst, Lizenzen für BA Logos, 4 Autoren
  HINWEISE.md
  Latex/bilder/.gitkeep
  Latex/bilder/ba-gc-logo.png
  Latex/bilder/ba_glauchau_logo.svg
  Latex/inhalt/Anhang.tex
  Latex/inhalt/Kapitel1.tex
  Latex/main.tex
  Latex/metadaten.sty
  Latex/vorlage/Abstract_Freigabeerklärung_Bachelorthesis.tex
  Latex/vorlage/Erklärung_3Autoren.tex
  Latex/vorlage/Erklärung_4Autoren.tex
  Latex/vorlage/Erklärung_Praxisbeleg.tex
  Latex/vorlage/Titelseite_3Autoren.tex
  Latex/vorlage/Titelseite_4Autoren.tex
  Latex/vorlage/Titelseite_Praxisbeleg.tex
  Latex/vorlage/ba-gc-logo.png
  Latex/vorlage/ba-gc-logo.svg
  Latex/vorlage/dirtree_file.svg
  Latex/vorlage/dirtree_folder.svg
  Latex/vorlage/vorlage.tex
  README.md
Labels: enhancement
