Repository ba-latex/Vorlage-Latex, pull requests merged in 2022-07, with the labels that each got.

#175 Formel-Beispiel eingebaut und Formel-Caption korrekt formatiert
  HINWEISE.md
  Latex/vorlage/Doku-Test.tex
  Latex/vorlage/vorlage.tex
Labels: bug, documentation

#177 Bugfix - andere Captions nicht zentrieren
  HINWEISE.md
  Latex/vorlage/Doku-Test.tex
  Latex/vorlage/vorlage.tex
Labels: bug

#178 Custom Command für Formeln
  HINWEISE.md
  Latex/vorlage/Doku-Test.tex
  Latex/vorlage/vorlage_commands.tex
Labels: enhancement

#181 Erweiterung und Umstrukturierung
  HINWEISE.md
Labels: documentation

#191 4.0 - Klassenkampf
  Latex/inhalt/Abkürzungen.tex
  Latex/inhalt/Anhang.tex
  Latex/light/main.tex
  Latex/main.tex
  Latex/vorlage/Doku-Test.tex
  Latex/vorlage/Erklärung_1Autor.tex
  Latex/vorlage/Erklärung_common.tex
  Latex/vorlage/Freigabeerklärung_Bachelorthesis.tex
  Latex/vorlage/Platzhalter_Themenblatt.tex
  Latex/vorlage/Sperrvermerk.tex
  Latex/vorlage/vorlage.tex
  Latex/vorlage/vorlage_commands.tex
Labels: enhancement

#192 4.0.0 Klassenkampf
  Latex/inhalt/Abkürzungen.tex
  Latex/inhalt/Anhang.tex
  Latex/light/main.tex
  Latex/main.tex
  Latex/vorlage/Doku-Test.tex
  Latex/vorlage/Erklärung_1Autor.tex
  Latex/vorlage/Erklärung_common.tex
  Latex/vorlage/Freigabeerklärung_Bachelorthesis.tex
  Latex/vorlage/Platzhalter_Themenblatt.tex
  Latex/vorlage/Sperrvermerk.tex
  Latex/vorlage/vorlage.tex
  Latex/vorlage/vorlage_commands.tex
Labels: enhancement, release

#193 Fußnotennummerierung korrigiert
  Latex/vorlage/vorlage.tex
Labels: bug

#194 4.0.1 - FootnoteFix
  Latex/vorlage/vorlage.tex
Labels: bug, release

#197 Zitierformat, vgl. Zitat, MDs angepasst
  HINWEISE.md
  Latex/vorlage/Doku-Test.tex
  Latex/vorlage/vorlage.tex
  README.md
Labels: enhancement

#201 Quelle Vorlage angepasst
  Latex/literatur.bib
Labels: enhancement

#203 Typo
  HINWEISE.md
Labels: bug, documentation

#204 Vspace vor Minted Umgebungen (und weniger militante Positionierung)
  Latex/vorlage/vorlage_subs/minted.tex
Labels: enhancement

#202 Cleanup + Vorlage Quelle angepasst + Minted fix
  HINWEISE.md
  Latex/inhalt/Anhang.tex
  Latex/literatur.bib
  Latex/main.tex
  Latex/main_abstract.tex
  Latex/vorlage/Doku-Test.tex
  Latex/vorlage/Erklärung/1Autor.tex
  Latex/vorlage/Erklärung/2Autoren.tex
  Latex/vorlage/Erklärung/3Autoren.tex
  Latex/vorlage/Erklärung/4Autoren.tex
  Latex/vorlage/Erklärung/common.tex
  Latex/vorlage/bilder/ba-gc-logo.png
  Latex/vorlage/bilder/ba-gc-logo.svg
  Latex/vorlage/bilder/dirtree_file.svg
  Latex/vorlage/bilder/dirtree_folder.svg
  Latex/vorlage/vorlage.tex
  Latex/vorlage/vorlage_subs/captions.tex
  Latex/vorlage/vorlage_subs/custom_commands.tex
  Latex/vorlage/vorlage_subs/dirtree.tex
  Latex/vorlage/vorlage_subs/kopf_fußzeile.tex
  Latex/vorlage/vorlage_subs/literatur_zitate.tex
  Latex/vorlage/vorlage_subs/minted.tex
  Latex/vorlage/vorlage_subs/pdf_metadaten.tex
  Latex/vorlage/vorlage_subs/umbrüche.tex
  Latex/vorlage/vorlage_subs/verzeichnisse.tex
  README.md
Labels: enhancement, release
